#spring:
#  profiles:
#    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://database-1.c184wlxydqqd.us-west-2.rds.amazonaws.com:5432/aktheraja
    username: aktheraja
    password: 123456789
    pool-size: 30

