spring:
  profiles:
    active: @spring.profiles.active@

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:postgresql://database-1-instance.c184wlxydqqd.us-west-2.rds.amazonaws.com:5432/aktheraja
    username: aktheraja
    password: postgres
    pool-size: 30

